version: "3"
services:
  mongo:
    image: mongo
    command: -smallfiles -nojournal
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
  mongo-express:
    depends_on:
      - "mongo"
    image: mongo-express
    ports:
      - "8081:8081"

volumes:
  db-data:
